name: law_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4 
  google_sign_in: ^6.2.1  # Changed from 7.1.0 to more stable version
  firebase_auth: ^4.17.7
  firebase_core: ^2.31.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LexAid.png"

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png


