// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABlJ18IHJ5A5E4F3-6ow1FT1jANgnKMRU',
    appId: '1:728675736938:web:c2d0a19d877572940c5913',
    messagingSenderId: '728675736938',
    projectId: 'law-and-order-app-64ed3',
    authDomain: 'law-and-order-app-64ed3.firebaseapp.com',
    storageBucket: 'law-and-order-app-64ed3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYVOWErddopIQUGoexTlfgBqlHhgvWXow',
    appId: '1:728675736938:android:cb50dc136ecf5c830c5913',
    messagingSenderId: '728675736938',
    projectId: 'law-and-order-app-64ed3',
    storageBucket: 'law-and-order-app-64ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcaGbJVSbcWI82PTMyMxzYx2gRMmZFf4',
    appId: '1:728675736938:ios:cf3e507df7886c0d0c5913',
    messagingSenderId: '728675736938',
    projectId: 'law-and-order-app-64ed3',
    storageBucket: 'law-and-order-app-64ed3.firebasestorage.app',
    iosBundleId: 'com.example.lawApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkcaGbJVSbcWI82PTMyMxzYx2gRMmZFf4',
    appId: '1:728675736938:ios:cf3e507df7886c0d0c5913',
    messagingSenderId: '728675736938',
    projectId: 'law-and-order-app-64ed3',
    storageBucket: 'law-and-order-app-64ed3.firebasestorage.app',
    iosBundleId: 'com.example.lawApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABlJ18IHJ5A5E4F3-6ow1FT1jANgnKMRU',
    appId: '1:728675736938:web:84101af2a987794e0c5913',
    messagingSenderId: '728675736938',
    projectId: 'law-and-order-app-64ed3',
    authDomain: 'law-and-order-app-64ed3.firebaseapp.com',
    storageBucket: 'law-and-order-app-64ed3.firebasestorage.app',
  );
}
